services:
  app:
    platform: linux/amd64
    build:
      context: .
      args:
        NEXT_PUBLIC_CDP_WRITEKEY: ${NEXT_PUBLIC_CDP_WRITEKEY}
        NEXT_PUBLIC_CDP_ENDPOINT: ${NEXT_PUBLIC_CDP_ENDPOINT}
        NEXT_PUBLIC_DISCOVER_DEFAULT_SCRIPT: ${NEXT_PUBLIC_DISCOVER_DEFAULT_SCRIPT}
        NEXT_PUBLIC_INTERACT_ENDPOINT: ${NEXT_PUBLIC_INTERACT_ENDPOINT}
        NEXT_PUBLIC_INTERACT_CHANNEL_NAME: ${NEXT_PUBLIC_INTERACT_CHANNEL_NAME}
        NEXT_PUBLIC_INTERACTION_POINT: ${NEXT_PUBLIC_INTERACTION_POINT}
        NEXT_PUBLIC_GA_MEASUREMENT_ID: ${NEXT_PUBLIC_GA_MEASUREMENT_ID}
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
    image: ${DEPLOY_IMAGE_NAME}
    container_name: ${CONTAINER_NAME:-${DEPLOY_CONTAINER_PREFIX}-app}
    restart: unless-stopped
    ports:
      - "${DEPLOY_SITE_PORT}:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - INDUSTRY_VERTICAL=${INDUSTRY_VERTICAL:-energy}
      - NEXT_PUBLIC_CDP_WRITEKEY=${NEXT_PUBLIC_CDP_WRITEKEY}
      - NEXT_PUBLIC_CDP_ENDPOINT=${NEXT_PUBLIC_CDP_ENDPOINT}
      - NEXT_PUBLIC_DISCOVER_DEFAULT_SCRIPT=${NEXT_PUBLIC_DISCOVER_DEFAULT_SCRIPT}
      - NEXT_PUBLIC_INTERACT_ENDPOINT=${NEXT_PUBLIC_INTERACT_ENDPOINT}
      - NEXT_PUBLIC_INTERACT_CHANNEL_NAME=${NEXT_PUBLIC_INTERACT_CHANNEL_NAME}
      - NEXT_PUBLIC_INTERACTION_POINT=${NEXT_PUBLIC_INTERACTION_POINT}
      - NEXT_PUBLIC_GA_MEASUREMENT_ID=${NEXT_PUBLIC_GA_MEASUREMENT_ID}
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    working_dir: /app
    command: ["docker-entrypoint-multitenant.sh", "node", "server.js"]
    networks:
      - multitenant-network

networks:
  multitenant-network:
    name: multitenant-network
    external: true
